// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0nep_xXqULsPALOz79cgjAzZ18EUsY80',
    appId: '1:630957517174:web:0ec29dbd231e41870e3257',
    messagingSenderId: '630957517174',
    projectId: 'flutter-humi-writer',
    authDomain: 'flutter-humi-writer.firebaseapp.com',
    storageBucket: 'flutter-humi-writer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzH4vw54vRjQknqVGiQ_NOyOyFFUx538',
    appId: '1:630957517174:android:d689d5d61569e78a0e3257',
    messagingSenderId: '630957517174',
    projectId: 'flutter-humi-writer',
    storageBucket: 'flutter-humi-writer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD0W-NuvHwVHd8iJQgxkt48lOvbGP-B9k',
    appId: '1:630957517174:ios:3e3901511feea4640e3257',
    messagingSenderId: '630957517174',
    projectId: 'flutter-humi-writer',
    storageBucket: 'flutter-humi-writer.appspot.com',
    iosBundleId: 'com.yopheu.writer',
  );
}
